# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: #events
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs: #jobs tp be exeucuted
  build:
    runs-on: ubuntu-latest #ubuntu is preinstalled in Docker
#     runs-on: ${{matrix.os}}
#     strategy:
#       matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3 #checkout action: https://github.com/actions/checkout/blob/main/action.yml
    
    - name: Set up JDK 11 #prepare enviroment with java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
              
#   publish:
  
#       needs: build #tells github to run publish after build, otherwise github run build & publish in parallel

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4 #source:https://github.com/mr-smithers-excellent/docker-build-push
      with:
        image: willcsw/my-demo
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


# YOUTUBER NINA'S VERSION
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# name: Java CI with Gradle

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build-java:

#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8

#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew

#     - name: Build with Gradle
#       run: ./gradlew build

#     - name: Build and Push Docker Image
#       uses: mr-smithers-excellent/docker-build-push@v4
#       with:
#         image: nanajanashia/demo-app
#         registry: docker.io
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
         
